/*
 * This Java source file was generated by the Gradle 'init' task.
 */
import org.junit.Test;
import static org.junit.Assert.*;

import com.rxonda.Application;

public class LibraryTest {
    @Test public void testSomeLibraryMethod() {
        Application classUnderTest = new Application();
        assertNotNull("someLibraryMethod should return 'true'", classUnderTest);
    }
}
